# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_auto_20160310_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 10, 19, 33, 17, 697483, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 10, 19, 34, 6, 285647, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
