# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0004_auto_20160314_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
